### ISSUE TITLE
Wrong hash in ghcup-0.0.7.yaml for x86_64-apple-darwin-ghcup-0.1.17.7 binary?

### ISSUE THREAD

**Issue by konnik** [haskell/ghcup-metadata#23]
From ghcup-0.0.7.yaml:
```
         ...
          Darwin:
            unknown_versioning:
              dlUri: https://downloads.haskell.org/~ghcup/0.1.17.7/x86_64-apple-darwin-ghcup-0.1.17.7
              dlHash: d3d0644dc5d9b51ed1c345fc006e936e9284b3181e5a9cccf4cf70a7184398fe
          FreeBSD:
            '( >= 12 && < 13 )':
              dlUri: https://downloads.haskell.org/~ghcup/0.1.17.7/x86_64-freebsd12-ghcup-0.1.17.7
              dlHash: d3d0644dc5d9b51ed1c345fc006e936e9284b3181e5a9cccf4cf70a7184398fe
            '( >= 13 )':
              dlUri: https://downloads.haskell.org/~ghcup/0.1.17.7/x86_64-freebsd13-ghcup-0.1.17.7
              dlHash: d3d0644dc5d9b51ed1c345fc006e936e9284b3181e5a9cccf4cf70a7184398fe
```

The hash for Darwin binary is the same as FreeBSD binary. Is this really correct? I could not do a `ghcup upgrade` on my mac without first changing this to `9702f30c9374a122d79f7ef11170b34deb248a0f3cd92d671c0aab747be4add7` (the hash for the darwin binary pointed to by the url).
