### ISSUE TITLE
deb9 GHC installed on Debian 11, instead of deb10

### ISSUE THREAD

**Issue by liskin** [haskell/ghcup-metadata#8]
Steps to reproduce:

1. boot `https://cloud.debian.org/images/cloud/bullseye/20211011-792/debian-11-nocloud-amd64-20211011-792.qcow2` in qemu
2. `curl --proto '=https' --tlsv1.2 -sSf https://get-ghcup.haskell.org | sh`
3. observe that `https://downloads.haskell.org/~ghc/8.10.7/ghc-8.10.7-x86_64-deb9-linux.tar.xz` gets installed instead of the `deb10` variant, which is more appropriate (IMO)

Probable cause:

```
          Linux_Debian:
            '( >= 9 && < 10 )': &ghc-8107-64-deb9
              dlUri: https://downloads.haskell.org/~ghc/8.10.7/ghc-8.10.7-x86_64-deb9-linux.tar.xz
              dlSubdir: ghc-8.10.7
              dlHash: ced9870ea351af64fb48274b81a664cdb6a9266775f1598a79cbb6fdd5770a23
            '( >= 10 && < 11 )': &ghc-8107-64-deb10
              dlUri: https://downloads.haskell.org/~ghc/8.10.7/ghc-8.10.7-x86_64-deb10-linux.tar.xz
              dlSubdir: ghc-8.10.7
              dlHash: a13719bca87a0d3ac0c7d4157a4e60887009a7f1a8dbe95c4759ec413e086d30
            unknown_versioning: *ghc-8107-64-deb9
```

The above falls back to `deb9` for Debian 11.
Note that the fallback is also used with Debian testing or unstable, as these don't have any version in /etc/os-release.

(Same thing happens with GHC 9.2.1, it's not specific to old GHC versions.)
